export default {
  nav: {
    tableView: 'Çalışan Listesi (Tablo Görünümü)',
    listView: 'Çalışan Listesi (Liste Görünümü)',
    employees: 'Çalışanlar',
    addEmployee: 'Yeni Ekle',
  },
  employeeList: 'Çalışan Listesi',
  employee: {
    firstName: 'Ad',
    lastName: 'Soyad',
    email: 'E-posta',
    phone: 'Telefon',
    dateOfEmployment: 'İşe Başlama Tarihi',
    dateOfBirth: 'Doğum Tarihi',
    department: 'Departman',
    position: 'Pozisyon',
  },
  table: {
    actions: 'İşlemler',
  },
  buttons: {
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    add: 'Çalışan Ekle',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
    listFormat: 'Liste Formatı',
    tableFormat: 'Tablo Formatı',
  },
  messages: {
    confirmDelete: 'Bu çalışanı silmek istediğinizden emin misiniz?',
    confirmUpdate: 'Bu çalışanı güncellemek istediğinizden emin misiniz?',
    employeeAdded: 'Çalışan başarıyla eklendi',
    employeeUpdated: 'Çalışan başarıyla güncellendi',
    employeeDeleted: 'Çalışan başarıyla silindi',
    emailExists: 'Bu e-posta adresine sahip bir çalışan zaten mevcut',
    phoneExists: 'Bu telefon numarasına sahip bir çalışan zaten mevcut',
    requiredField: 'Bu alan zorunludur',
    invalidEmail: 'Lütfen geçerli bir e-posta adresi girin',
    invalidPhone: 'Lütfen geçerli bir telefon numarası girin',
    invalidAge: 'Çalışan en az 18 yaşında olmalıdır',
    noEmployeesYet: 'Henüz çalışan yok',
    noEmployeesFound: 'Çalışan bulunamadı',
    getStartedMessage: 'İlk çalışanınızı ekleyerek başlayın',
    adjustSearchMessage: 'Arama kriterlerinizi ayarlamayı deneyin',
  },
  placeholders: {
    searchEmployees: 'Çalışan ara...',
    enterFirstName: 'Ad girin',
    enterLastName: 'Soyad girin',
    enterEmail: 'E-posta adresi girin',
    enterPhone: 'Telefon numarası girin',
    selectDepartment: 'Departman seçin',
    selectPosition: 'Pozisyon seçin',
  },
  pagination: {
    showing: 'Gösteriliyor',
    of: '/',
    results: 'sonuç',
    previous: 'Önceki',
    next: 'Sonraki',
    page: 'Sayfa'
  },
  validation: {
    firstNameRequired: 'Ad zorunludur',
    firstNameTooShort: 'Ad en az 2 karakter olmalıdır',
    firstNameTooLong: 'Ad 50 karakteri geçmemelidir',
    firstNameInvalid: 'Ad geçersiz karakterler içeriyor',
    lastNameRequired: 'Soyad zorunludur',
    lastNameTooShort: 'Soyad en az 2 karakter olmalıdır',
    lastNameTooLong: 'Soyad 50 karakteri geçmemelidir',
    lastNameInvalid: 'Soyad geçersiz karakterler içeriyor',
    emailRequired: 'E-posta zorunludur',
    emailInvalid: 'Lütfen geçerli bir e-posta adresi girin',
    emailExists: 'Bu e-posta adresine sahip bir çalışan zaten mevcut',
    phoneRequired: 'Telefon zorunludur',
    phoneTooShort: 'Telefon numarası en az 10 haneli olmalıdır',
    phoneTooLong: 'Telefon numarası 15 haneyi geçmemelidir',
    phoneInvalid: 'Lütfen geçerli bir telefon numarası girin',
    dateOfBirthRequired: 'Doğum tarihi zorunludur',
    dateOfBirthInvalid: 'Lütfen geçerli bir doğum tarihi girin',
    dateOfBirthFuture: 'Doğum tarihi gelecekte olamaz',
    dateOfBirthTooYoung: 'Çalışan en az 16 yaşında olmalıdır',
    dateOfBirthTooOld: 'Lütfen doğum tarihini kontrol edin',
    dateOfEmploymentRequired: 'İşe başlama tarihi zorunludur',
    dateOfEmploymentInvalid: 'Lütfen geçerli bir işe başlama tarihi girin',
    dateOfEmploymentTooFuture: 'İşe başlama tarihi gelecekte 1 yıldan fazla olamaz',
    dateOfEmploymentBeforeBirth: 'İşe başlama tarihi doğum tarihinden önce olamaz',
    departmentRequired: 'Departman zorunludur',
    departmentInvalid: 'Lütfen geçerli bir departman seçin',
    positionRequired: 'Pozisyon zorunludur',
    positionInvalid: 'Lütfen geçerli bir pozisyon seçin'
  }
};
